<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

    <ItemGroup>
	    <None Update="Brain\Feelings\FeelingsData.json">
	      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	    </None>
	    <None Update="Brain\Thought\ThoughtData.json">
		    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	    </None>
	    <None Update="Members\Arms\ArmsData.json">
	      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	    </None>
	    <None Update="Members\Legs\LegsData.json">
	      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	    </None>
    </ItemGroup>

</Project>
